services:
  db:
    image: postgres:17
    user: root
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069" # web
    tty: true
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - PIP_BREAK_SYSTEM_PACKAGES=1
    volumes:
      - odoo-data:/var/lib/odoo
      - odoo-addons:/mnt/extra-addons
      - ./addons:/mnt/addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    restart: always
    command:
      sh -c "/usr/bin/odoo -c /etc/odoo/odoo.conf --dev=qweb,xml $OPTIONS"

volumes:
  odoo-data:
  odoo-addons:
  db-data:
